ANDROID_HOME=${HOME}/.local/share/android-sdk
ANDROID_SDK_ROOT=${HOME}/.local/share/android-sdk
ANDROID_AVD_HOME=${HOME}/.config/.android/avd
PATH=${HOME}/.local/share/android-sdk/platform-tools:${HOME}/.local/share/android-sdk/cmdline-tools/latest/bin:${HOME}/.local/share/android-sdk/emulator:${PATH}
