complete -c dotf -f
complete -c dotf -n __fish_use_subcommand -a apply -d 'Apply the resolved host'
complete -c dotf -n __fish_use_subcommand -a a -d 'Apply (alias)'
complete -c dotf -n __fish_use_subcommand -a remove -d 'Remove the last applied composition'
complete -c dotf -n __fish_use_subcommand -a u -d 'Remove (alias)'
complete -c dotf -n __fish_use_subcommand -a list -d 'List the resolved composition'
complete -c dotf -n __fish_use_subcommand -a l -d 'List (alias)'
complete -c dotf -n __fish_use_subcommand -a edit -d 'Open dotfiles in editor'
complete -c dotf -n __fish_use_subcommand -a e -d 'Edit (alias)'
complete -c dotf -n __fish_use_subcommand -a check -d 'Dry-run (show changes)'
complete -c dotf -n __fish_use_subcommand -a c -d 'Dry-run (alias)'
complete -c dotf -n __fish_use_subcommand -a status -d 'Check the resolved host'
complete -c dotf -n __fish_use_subcommand -a doctor -d 'Audit configuration and live capabilities'
complete -c dotf -n __fish_use_subcommand -a packages -d 'List resolved packages and Flatpaks'
complete -c dotf -n __fish_use_subcommand -a host -d 'Manage private host configuration'

complete -c dotf -n '__fish_seen_subcommand_from host' -a detect -d 'Detect host capabilities'
complete -c dotf -n '__fish_seen_subcommand_from host' -a configure -d 'Configure host choices'
complete -c dotf -n '__fish_seen_subcommand_from host' -a resolve -d 'Resolve the host composition'
complete -c dotf -n '__fish_seen_subcommand_from host' -a show -d 'Show the host composition'
complete -c dotf -n '__fish_seen_subcommand_from host' -a refresh -d 'Refresh detected capabilities'
complete -c dotf -n '__fish_seen_subcommand_from host' -a export -d 'Export portable choices'
complete -c dotf -n '__fish_seen_subcommand_from host' -a rollback -d 'Preview or restore a migration'
complete -c dotf -n '__fish_seen_subcommand_from host' -a retire -d 'Preview or remove the applied composition'
