complete -c dotf -f
complete -c dotf -n __fish_use_subcommand -a stow -d 'Stow packages (all if none specified)'
complete -c dotf -n __fish_use_subcommand -a s -d 'Stow (alias)'
complete -c dotf -n __fish_use_subcommand -a unstow -d 'Unstow packages'
complete -c dotf -n __fish_use_subcommand -a u -d 'Unstow (alias)'
complete -c dotf -n __fish_use_subcommand -a restow -d 'Restow packages'
complete -c dotf -n __fish_use_subcommand -a r -d 'Restow (alias)'
complete -c dotf -n __fish_use_subcommand -a list -d 'List available packages'
complete -c dotf -n __fish_use_subcommand -a l -d 'List (alias)'
complete -c dotf -n __fish_use_subcommand -a edit -d 'Open dotfiles in editor'
complete -c dotf -n __fish_use_subcommand -a e -d 'Edit (alias)'
complete -c dotf -n __fish_use_subcommand -a check -d 'Dry-run (show changes)'
complete -c dotf -n __fish_use_subcommand -a c -d 'Dry-run (alias)'
complete -c dotf -n '__fish_seen_subcommand_from stow s unstow u restow r check c' -a '(dotf list)'
