complete -c dotf -f
complete -c dotf -n __fish_use_subcommand -a apply -d 'Apply an allowed target'
complete -c dotf -n __fish_use_subcommand -a a -d 'Apply (alias)'
complete -c dotf -n __fish_use_subcommand -a remove -d 'Remove an allowed target'
complete -c dotf -n __fish_use_subcommand -a u -d 'Remove (alias)'
complete -c dotf -n __fish_use_subcommand -a list -d 'List available packages'
complete -c dotf -n __fish_use_subcommand -a l -d 'List (alias)'
complete -c dotf -n __fish_use_subcommand -a edit -d 'Open dotfiles in editor'
complete -c dotf -n __fish_use_subcommand -a e -d 'Edit (alias)'
complete -c dotf -n __fish_use_subcommand -a check -d 'Dry-run (show changes)'
complete -c dotf -n __fish_use_subcommand -a c -d 'Dry-run (alias)'
complete -c dotf -n __fish_use_subcommand -a status -d 'Check one profile'
complete -c dotf -n '__fish_seen_subcommand_from apply a remove u check c' -a '(dotf list | string trim)'
complete -c dotf -n '__fish_seen_subcommand_from status' -a 'desktop workstation'
