"""Neutral policy and role adapters. No host state or credentials live here."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LINUX_SKILLS = {"cachyos-host-audit"}
RETIRED = {"frontend-task", "reuse-first", "visual-direction"}


def instructions(client: str, platform: str, root: Path = ROOT) -> str:
    files = [root / "ai/rules/common.md", root / f"ai/adapters/{client}.md",
             root / f"ai/adapters/{platform}.md"]
    return "<!-- Generated by scripts/render-ai.py from ai/. Edit the source. -->\n\n" + "\n".join(
        path.read_text(encoding="utf-8").rstrip() + "\n" for path in files)


def roles(client: str, platform: str, root: Path = ROOT) -> dict[str, str]:
    result = {}
    for path in sorted((root / "ai/roles").glob("*.json")):
        role = json.loads(path.read_text(encoding="utf-8"))
        scout = role["name"] == "reuse-scout"
        body = role["instructions"].strip() + "\n\nEl agente principal ejecuta las pruebas. Usa solo herramientas de lectura. No ejecutes pruebas ni comandos que cambien estado.\n"
        if client == "codex":
            fields = dict(name=role["name"], description=role["description"],
                          model="gpt-5.6-luna" if scout else "gpt-5.6-sol",
                          model_reasoning_effort="low" if scout else "high", sandbox_mode="read-only")
            result[path.stem + ".toml"] = (
                "# Generated from ai/roles.\n" +
                "".join(f"{key} = {json.dumps(value, ensure_ascii=False)}\n" for key, value in fields.items()) +
                f"developer_instructions = {json.dumps(body, ensure_ascii=False)}\n")
        else:
            result[path.stem + ".md"] = (
                f"---\nname: {role['name']}\ndescription: {json.dumps(role['description'], ensure_ascii=False)}\n"
                "tools: Read, Glob, Grep, WebFetch, WebSearch\n" +
                ("model: haiku\n" if scout else "model: opus\neffort: high\n") +
                "---\n\n" + body)
    return result


def codex_outputs(root: Path = ROOT) -> dict[Path, str]:
    result = {root / "codex/.codex/AGENTS.md": instructions("codex", "linux", root)}
    result.update({root / "codex/.codex/agents" / name: value
                   for name, value in roles("codex", "linux", root).items()})
    return result
