"""Neutral policy and role adapters. No host state or credentials live here."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LINUX_SKILLS = {"cachyos-host-audit"}
RETIRED = {"frontend-task", "reuse-first", "visual-direction"}
# Invocation policy for every skill; unlisted skills fail the checks.
# - IMPLICIT: the model picks them from their description.
# - NAMED: other skills route to them by name. Claude lists only the name
#   (skillOverrides "name-only"), so they cost almost no context yet stay invocable.
# - USER: only the user runs them as /name (disable-model-invocation: true).
# Codex has no name-only mode: NAMED and USER both get allow_implicit_invocation = false.
IMPLICIT_SKILLS = frozenset({
    "cachyos-host-audit", "clarify-change", "debug-web-flow", "engineering-flow",
    "handoff", "linear-workflow", "playwright-cli", "research-primary-sources",
    "review-web-pr", "spec-and-standards-review", "systematic-debugging", "tessera",
    "verification-before-completion",
})
NAMED_SKILLS = frozenset({"test-driven-development", "verify", "verify-web-change"})
USER_SKILLS = frozenset({"codebase-design", "domain-modeling", "to-tickets"})
EXPLICIT_SKILLS = NAMED_SKILLS | USER_SKILLS


def instructions(client: str, platform: str, root: Path = ROOT) -> str:
    files = [root / "ai/rules/common.md", root / f"ai/adapters/{client}.md",
             root / f"ai/adapters/{platform}.md"]
    return "<!-- Generated by scripts/render-ai.py from ai/. Edit the source. -->\n\n" + "\n".join(
        path.read_text(encoding="utf-8").rstrip() + "\n" for path in files)


ROLE_FOOTER = ("\n\nThe main agent runs the tests. Use read-only tools only. "
               "Do not run tests or commands that change state.\n")


def roles(client: str, platform: str, root: Path = ROOT) -> dict[str, str]:
    """Render each neutral role for one client; models live in the role data."""
    result = {}
    for path in sorted((root / "ai/roles").glob("*.json")):
        role = json.loads(path.read_text(encoding="utf-8"))
        body = role["instructions"].strip() + ROLE_FOOTER
        settings = role[client]
        if client == "codex":
            fields = dict(name=role["name"], description=role["description"], model=settings["model"],
                          model_reasoning_effort=settings["effort"], sandbox_mode="read-only")
            result[path.stem + ".toml"] = (
                "# Generated from ai/roles.\n" +
                "".join(f"{key} = {json.dumps(value, ensure_ascii=False)}\n" for key, value in fields.items()) +
                f"developer_instructions = {json.dumps(body, ensure_ascii=False)}\n")
        else:
            lines = [f"name: {role['name']}",
                     f"description: {json.dumps(role['description'], ensure_ascii=False)}",
                     "tools: " + ", ".join(settings["tools"]),
                     f"model: {settings['model']}"]
            lines += [f"{key}: {settings[key]}" for key in ("effort", "maxTurns") if key in settings]
            result[path.stem + ".md"] = "---\n" + "\n".join(lines) + "\n---\n\n" + body
    return result


def hook_scripts(root: Path = ROOT) -> dict[str, str]:
    """Client-neutral hook programs deployed as regular files under ~/.claude/hooks."""
    return {path.name: path.read_text(encoding="utf-8")
            for path in sorted((root / "ai/hooks").glob("*.py"))}


def codex_outputs(root: Path = ROOT) -> dict[Path, str]:
    result = {root / "codex/.codex/AGENTS.md": instructions("codex", "linux", root)}
    result.update({root / "codex/.codex/agents" / name: value
                   for name, value in roles("codex", "linux", root).items()})
    return result
